### ISSUE TITLE
i have an internal server error

### ISSUE THREAD

**Issue by Bloxcitylaravel** [Aeplexi/ECS#2]
When I go on localhost:5000/auth/application to submit an application, I get a code 0 internal server error. What do I do?

**Comment by Aeplexi** [comment]
show a pic

**Comment by Bloxcitylaravel** [comment]
ok

**Comment by Bloxcitylaravel** [comment]
https://i.imgur.com/mN3Ebwv.png

**Comment by Aeplexi** [comment]
dm me on discord (aep without the tag)
